# Generated by Django 4.2.26 on 2025-11-27 14:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('resources', '0002_category_resource_category'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='category',
            options={'verbose_name_plural': 'Categories'},
        ),
    ]
