# Generated by Django 4.2.26 on 2025-12-01 09:44

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('resources', '0003_alter_category_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='resource',
            name='favorites',
            field=models.ManyToManyField(blank=True, related_name='favorite_resources', to=settings.AUTH_USER_MODEL),
        ),
    ]
